language: python
dist: bionic
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - sudo apt update
  - python -m pip install --upgrade pip
  - pip install .
######################################################
script: 
  - sh test.sh
after_success:
  - coveralls
